import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import StyledJsxRegistry from "./registry";
import { Store } from "./context/store";
import Header from "./components/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJs+Gluestack",
  description: "Generated by nextjs13 and gluestack",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="gs">
      <body className={inter.className}>
        <Store>
          <Providers>
            <Header />
            <StyledJsxRegistry>{children}</StyledJsxRegistry>
          </Providers>
        </Store>
      </body>
    </html>
  );
}
